DROP TABLE ACCOUNT
IF EXISTS;
CREATE TABLE ACCOUNT (
  account_id INTEGER IDENTITY PRIMARY KEY,
  username   VARCHAR(45) NOT NULL,
  password   VARCHAR(60) NOT NULL
);
DROP TABLE POST
IF EXISTS;
CREATE TABLE POST (
  post_id  INTEGER IDENTITY PRIMARY KEY,
  title    VARCHAR(100) DEFAULT NULL,
  text     VARCHAR(10000) NOT NULL,
  date     TIMESTAMP      NOT NULL,
  owner_id INTEGER        NOT NULL
);
DROP TABLE COMMENT
IF EXISTS;
CREATE TABLE COMMENT (
  comment_id INTEGER IDENTITY PRIMARY KEY,
  text       VARCHAR(2000) NOT NULL,
  owner_id   INTEGER       NOT NULL,
  post_id    INTEGER       NOT NULL,
  date       TIMESTAMP     NOT NULL
);
DROP TABLE PROFILE
IF EXISTS;
CREATE TABLE PROFILE (
  profile_id INTEGER PRIMARY KEY,
  email      VARCHAR(60) DEFAULT NULL,
  firstname  VARCHAR(45) DEFAULT NULL,
  lastname   VARCHAR(45) DEFAULT NULL,
  birthdate  DATE        DEFAULT NULL,
  gender     VARCHAR(10) DEFAULT 'U',
  country    VARCHAR(45) DEFAULT NULL,
  city       VARCHAR(45) DEFAULT NULL,
  job        VARCHAR(45) DEFAULT NULL,
  about      VARCHAR(45) DEFAULT NULL
);
DROP TABLE TAG
IF EXISTS;
CREATE TABLE TAG (
  tag_id      INTEGER IDENTITY PRIMARY KEY,
  name        VARCHAR(45) NOT NULL,
  author_id   INTEGER     NOT NULL,
  description VARCHAR(1000) DEFAULT NULL,
  image_url   VARCHAR(100)  DEFAULT NULL,
  posts_count SMALLINT      DEFAULT NULL,
  date        DATETIME    NOT NULL
);

DROP TABLE TAG_OWNER
IF EXISTS;
CREATE TABLE TAG_OWNER (
  post_id_fk INTEGER NOT NULL,
  tag_id_fk  INTEGER NOT NULL
);
